// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA579feKEOm5ZUKWT32Cg1zmX1b8_z8ux8',
    appId: '1:742936221921:web:6a86cb58d7b37e72ddbfa0',
    messagingSenderId: '742936221921',
    projectId: 'article-app-60905',
    authDomain: 'article-app-60905.firebaseapp.com',
    storageBucket: 'article-app-60905.firebasestorage.app',
    measurementId: 'G-N8HSX4Y5BF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcMtRVj-m7o60_YOMlIxqWmvYFY0kFAKg',
    appId: '1:742936221921:android:645ab36a25a3b5a5ddbfa0',
    messagingSenderId: '742936221921',
    projectId: 'article-app-60905',
    storageBucket: 'article-app-60905.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZg7jFYoKSTUOfLl-kXjPM2ddT48AwbkY',
    appId: '1:742936221921:ios:8fa881ed2d184fd4ddbfa0',
    messagingSenderId: '742936221921',
    projectId: 'article-app-60905',
    storageBucket: 'article-app-60905.firebasestorage.app',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZg7jFYoKSTUOfLl-kXjPM2ddT48AwbkY',
    appId: '1:742936221921:ios:8fa881ed2d184fd4ddbfa0',
    messagingSenderId: '742936221921',
    projectId: 'article-app-60905',
    storageBucket: 'article-app-60905.firebasestorage.app',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA579feKEOm5ZUKWT32Cg1zmX1b8_z8ux8',
    appId: '1:742936221921:web:71e043748da7f8cbddbfa0',
    messagingSenderId: '742936221921',
    projectId: 'article-app-60905',
    authDomain: 'article-app-60905.firebaseapp.com',
    storageBucket: 'article-app-60905.firebasestorage.app',
    measurementId: 'G-30YK9PBVYJ',
  );
}
